### ISSUE TITLE
Question about DICE (Metric and Loss)

### ISSUE THREAD

**Issue by russchua** [trypag/torchmed#3]
Good day Pierre-Antoine Ganaye,

First and foremost, thank you for releasing code for torchmed.
I was just wondering if you could explain the difference between the DICE that you have as a metric and as a loss?

In particular, I note that for your metric, you only report the dice scores of each class in the ground truth labels.

However, in your loss, you divide by all the classes in the union of the ground truth labels and your predicted labels. Could you explain why this is so?

Thank you!

**Comment by trypag** [comment]
Hello @calciver,
Thank you for the nice words :)
The difference is really simple, the dice metric implements the original definition of the dice, while the dice loss implements a differentiable version that you can use during optimization. The metric implementation involves the argmax operator which cannot be used praticaly.

Your interpretation of the code is correct, in the loss the value is normalized so that the final value is bounded between 0 and 1.

**Comment by russchua** [comment]
Good day @trypag!

Wow, thank you so much for the swift response! 

If I may, I would like to ask another follow up question about options in implementing **DICE Loss**:
Let GT be Ground Truth Labels, P be Predicted Labels
Why do you choose Option 1 instead of Option 2 below?

1. Divide by class count of (GT ∪ P) to get the average DICE per label/prediction
2. Divide by class count of (GT) to get the average DICE per label/prediction

Also wondering if there is any reason why option 2 might not perform as well as option 1?

The reason I ask this is because some 2D slices of the brain do not have certain classes that exist in other slices (but appear in the prediction and have 0 intercept). Not excluding the effect of these Missing_Classes from the denominator could lead the DICE coefficient/metric to be smaller in images with less classes than those with more (because we divide by a larger denominator). This in turn results in a larger average DICE loss for these images with less classes.

Thank you so much!
Have a great day ahead!

**Comment by trypag** [comment]
Hello,

> Why do you choose Option 1 instead of Option 2 below?

Are you referring to the [denominator](https://github.com/trypag/torchmed/blob/master/torchmed/utils/loss.py#L19) or the [normalization](https://github.com/trypag/torchmed/blob/master/torchmed/utils/loss.py#L26) ?

I will consider you are talking about the denominator.
I implemented this loss based on the originial definition of the dice metric and also on other implementations available out there. I did not make personal choices during the implementation. I will try to answer your questions in an open way.

>  Why do you choose Option 1 instead of Option 2 below?

If GT and P are equal then the numerator should be 2, the denominator should also be equal to 2 in order to obtain a dice bounded between 0 and 1. 
With option 2 it would require to remove the factor 2 in the numerator. There might be a justification of why option 1 is better than option 2, actually I have never seen option 2 used by anyone, we just stick to the good old definition. 

Intuitively, I would say that the numerator enforces alignment of the masks **while the denominator will indicate the positions where the probabilities can be lowered**.

I agree with your comment on the effect of the number of classes, you can have a look at [the generalized dice](https://arxiv.org/pdf/1707.03237.pdf) loss if you want.

**Comment by russchua** [comment]
Good day @trypag,

Thank you for your response once again! I am actually referring to the normalization. You have a DICE score for each class. However, to report a DICE loss, I note that we divide by a different number of classes in Option 1 (all classes that exist regardless of GT or P) vs Option 2 (only for each class that exists in GT).

**Comment by trypag** [comment]
I see now, it seems legit and should be tested :)
Though it's a little bit complex to implement cause we average all classes over images. First you will have to count the number of structures in each image and implement the normalization adaptively for each.
